# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "Light rum")
Ingredient.create(name: "Applejack")
Ingredient.create(name: "Gin")
Ingredient.create(name: "Dark rum")
Ingredient.create(name: "Sweet Vermouth")
Ingredient.create(name: "Strawberry Schnapps")
Ingredient.create(name: "Scotch")
Ingredient.create(name: "Apricot Brandy")
Ingredient.create(name: "Triple sec")
Ingredient.create(name: "Southern Comfort")
Ingredient.create(name: "Lemon Vodka")
Ingredient.create(name: "Blendend Whiskey")
Ingredient.create(name: "Dry Vermouth")
Ingredient.create(name: "Amaretto")
Ingredient.create(name: "Tea")
Ingredient.create(name: "Champagne")
Ingredient.create(name: "Coffee liqueur")
Ingredient.create(name: "Bourdbon")
Ingredient.create(name: "Tequila")
Ingredient.create(name: "Bitters")
Ingredient.create(name: "Sugar")
Ingredient.create(name: "Kahlua")
Ingredient.create(name: "Watermelon")
Ingredient.create(name: "Lime juice")
Ingredient.create(name: "Irish Whiskey")
Ingredient.create(name: "Apple Brandy")
Ingredient.create(name: "Rum")
Ingredient.create(name: "Red wine")
Ingredient.create(name: "Creme de Cacao")
Ingredient.create(name: "Milk")
Ingredient.create(name: "Apple Juice")

Cocktail.create(name: "Mojito")
Cocktail.create(name: "Royal Mojito")
Cocktail.create(name: "Margarita")
Cocktail.create(name: "Daiquiri")


